#!/usr/bin/env bash
# build a system based on the dotfiles in this repository

mkdir -p ~/projects ~/.config/nvim ~/.config/kitty

ln nvim.lua ~/.config/nvim/init.lua
ln kitty.conf ~/.config/kitty/kitty.conf
ln git ~/.gitconfig
sudo ln nix.nix /etc/nixos/configuration.nix

echo >> ~/.bashrc
echo "source ~/projects/dots/bash" >> ~/.bashrc
source ~/.bashrc

echo "don't forget to copy sensitive files from ~/sync/recovery/buildsystem/"
ls "~/sync/recovery/buildsystem/"
