#!/bin/bash
# uses wl-clipboard [https://github.com/bugaevc/wl-clipboard]

PASSWORDS=/home/shinysocks/sync/archive/recovery/passwords 

function clear_clip {
  sleep 30 ; wl-copy ""
}

INFO=$(sudo -k cat $PASSWORDS | grep -m 1 $1)
echo -n $INFO | cut -d "|" -f2 | tr -d '\n' | wl-copy
clear_clip &

