[mov-cli]
version = 1
player = "mpv"
editor = "nvim"
fzf = false

[mov-cli.scrapers]
default = "films.default"

[mov-cli.plugins]
films = "film-central"

[mov-cli.downloads]
save_path = "/home/shinysocks/desktop/movies/"
