#!/bin/bash

# custom functions
function spotdl { python3 -m spotdl download "$1" --output ~/sync/tunes; }
function ytdl { yt-dlp "$1" --extract-audio --audio-format mp3 -o "$HOME/desktop/%(title)s.mp3"; }
function upload { curl -# https://shinysocks.net/upload -T "$1" | cat; }

# environment variables for functional editors
export PATH="/home/shinysocks/.local/bin:/usr/local/texlive/2024/bin/x86_64-linux$PATH"
export VISUAL="/home/linuxbrew/.linuxbrew/bin/nvim"
export EDITOR="/home/linuxbrew/.linuxbrew/bin/nvim"
export tunes="/home/shinysocks/sync/tunes/"
export memories="/home/shinysocks/sync/memories/"
export DXVK_AYSNC=1

# custom aliases
alias dots='/usr/bin/git --git-dir=$HOME/projects/dots --work-tree=$HOME'
alias l='ls -htlA'
alias update='sudo apt update -y ; sudo apt upgrade -y; sudo apt autoremove -y ; brew upgrade ; brew cleanup ; bash ~/.local/bin/backup_packages'
alias ssh="kitty +kitten ssh"
alias croc='croc --overwrite --yes'
alias nmtui='nmcli -p dev wifi rescan ; nmtui'
alias zzz='systemctl suspend ; exit'
alias ..='cd ..'

eval "$(starship init bash)"
source "$HOME/.cargo/env"
. "$HOME/.cargo/env"
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# delete screenshots directory
rm -rf ~/Screenshots

# unlimited history size
HISTSIZE=-1
HISTFILESIZE=-1
