#!/bin/bash

# custom functions
function spotdl { ~/.local/bin/spotdl download "$1" --output ~/sync/tunes; }
function bgcolor { gsettings set org.gnome.desktop.background primary-color "'#$1'"; }
function cat { batcat $@; }
function pirate { mov-cli -s films "$@"; }

# environment variables for functional editors
export PATH="/home/shinysocks/.local/bin:/home/shinysocks/.rainy$PATH"
export VISUAL="/home/shinysocks/.cargo/bin/hx"
export EDITOR="/home/shinysocks/.cargo/bin/hx"
export tunes="/home/shinysocks/sync/tunes/"
export memories="/home/shinysocks/sync/memories/"

# custom aliases
alias magic='env LUTRIS_SKIP_INIT=1 lutris lutris:rungameid/16'
alias dots='/usr/bin/git --git-dir=$HOME/projects/dots --work-tree=$HOME'
alias downup='docker compose down ; docker compose up -d'
alias l='ls -htlA'
alias update='sudo apt update -y ; sudo apt upgrade -y; sudo apt autoremove -y'
alias ssh="kitty +kitten ssh"
alias croc='croc --overwrite --yes'
alias nmtui='nmcli -p dev wifi rescan ; nmtui'
alias zzz='systemctl suspend ; exit'
alias ..='cd ..'

eval "$(starship init bash)"
source "$HOME/.cargo/env"
. "$HOME/.cargo/env"
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
export MANPAGER="sh -c 'col -bx | batcat -l man -p'"

# tunnel 8888 out
launch /usr/bin/ssh -fNR 8888:localhost:8888 pie


