#!/bin/bash -i

# this script should be run from the "dots" repository root.

# install essentials
sudo apt install build-essential curl cmake 

# create necessary directories
mkdir -p ~/projects ~/.config/nvim ~/.config/kitty

# install homebrew
NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# link configs from dots/
ln init.lua ~/.config/nvim/init.lua
ln kitty.conf ~/.config/kitty/kitty.conf
ln gitconfig ~/.gitconfig

# source bash config in bashrc
echo >> ~/.bashrc
echo "source ~/projects/dots/bash" >> ~/.bashrc

source ~/.bashrc

# install packages
/home/linuxbrew/.linuxbrew/bin/brew install "$(cat brewlist)"

# install spotdl
python3 -m pip install spotdl --break-system-packages

echo "need to source ~/.bashrc"
echo "run rsync and link bash.history and .git-credentials"

