#!/bin/bash

git status &> /dev/null

if [ $? -eq 0 ]; then

  gum style $(git branch --show-current) --foreground="#50C878"
  echo
  git status -s
  git add .

  CHANGES="$(echo $(git status -s | wc -l))"
  MESSAGE=$(gum input --prompt "commit: " --placeholder "made changes to $CHANGES files..")

  gum confirm "push $CHANGES files to remote?" --affirmative="send it!" --negative="nevermind" \
  && git commit -q -m "$MESSAGE" && gum spin --title "pushing.." git push || git restore --staged .

else
  gum style "there's no git repo here" --foreground="#F38BA8"
fi

echo done.
