#!/bin/bash

IFS=$'\n'

mkdir -p ~/nokia

sudo mount -t drvfs D: ~/nokia

for file in $(ls ~/sync/tunes/ -ht | head -n 20)
do
    cp -v -n ~/sync/tunes/"$file" ~/nokia/Audio/"$file"
done

for file in $(ls ~/sync/tunes/ | shuf | head -n 300)
do
    cp -v -n ~/sync/tunes/"$file" ~/nokia/Audio/"$file"
done

sleep 10
sudo umount ~/nokia && echo "unmounted nokia"
rm -rf ~/nokia
