#!/bin/bash
# rebuild pieces created by:
#   `split -n 4 sync.bak`
cat x* > sync.bak

# remove pieces
rm -r xa*

# password decrypt archive
gpg -o sync.bak.decrypt -d sync.bak

# extract tarball
tar -xf sync.bak.decrypt
