#!/bin/bash

cd ~/sync/memories/

while :
do
    PREV_NAME=$(ls -1 | grep Original | shuf | head -n 1)

    viu "$PREV_NAME"
    echo Current Name: $PREV_NAME

    read -p "Enter new name: " NEW_NAME

    [ ${#NEW_NAME} -ge 2 ] && mv "$PREV_NAME" $NEW_NAME || echo "not renaming"
done
