general {
    output_format = "dzen2"
    colors = true
    interval = 5
}

order += "battery all"
order += "tztime local"

battery all {
    format = "🔋 %percentage %remaining"
}

tztime local {
    format = "%m-%d-%Y %H:%M:%S"
}
