theme = "catppuccin_americano"

[editor]
true-color = true
auto-save = true
auto-format = false
line-number = "absolute"
# auto-pairs = true

# completion
completion-trigger-len = 0 # how many chars until autocompletion pops up
idle-timeout = 0 # how long until autocomplete happens
preview-completion-insert = true # insert completion when selected

gutters = ["line-numbers", "spacer", "diff"]

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-base-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "spacer", "version-control", "spacer", "spacer"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false # false means show hidden files

[editor.smart-tab]
enable = true # not sure..

